### ISSUE TITLE
How can I take Box client_id and box_client_secret??

### ISSUE THREAD

**Issue by ivanoterouvigo** [Developer-Autodesk/model.derivative-nodejs-box.viewer#1]
export BOX_CLIENT_ID=<<YOUR CLIENT ID FROM BOX DEVELOPER>>
export BOX_CLIENT_SECRET=<<YOUR BOX CLIENT SECRET>>

**Comment by leefsmp** [comment]
You have to request those keys on the box developer portal, signup for an account and so on ...
https://developer.box.com
