### ISSUE TITLE
Problem with npm run dev

### ISSUE THREAD

**Issue by ivanoterouvigo** [Developer-Autodesk/model.derivative-nodejs-box.viewer#2]
I run all steps like you say in readme and I have this error.

![model_viewer_002](https://cloud.githubusercontent.com/assets/11814769/18252644/b0e5a718-738f-11e6-90ed-e14c7b63609d.png)

What I need to do more??

**Comment by ivanoterouvigo** [comment]
![model_viewer_003](https://cloud.githubusercontent.com/assets/11814769/18252763/7aca9c1e-7390-11e6-92f2-787618edd532.png)

**Comment by augustogoncalves** [comment]
are you running that on Linux? 
what's your nodeJS version? (node --version) 
can you add more info that's on your log file?
this doesn't seem like a problem with the source, but with your NodeJS or NPM install.

**Comment by ivanoterouvigo** [comment]
![info_about_pc_002](https://cloud.githubusercontent.com/assets/11814769/18265503/5c359214-7416-11e6-8220-030d53dd8345.png)

[npm-debug.zip](https://github.com/Developer-Autodesk/model.derivative-nodejs-box.viewer/files/456165/npm-debug.zip)

**Comment by augustogoncalves** [comment]
so you definitely need to update your node & npm installs, your version seems quite old... we tested with node 4.4.3 and npm 2.15.1, and yours is below:

info using npm@1.4.28
info using node@v0.10.37

**Comment by ivanoterouvigo** [comment]
Thanks it work fine.

I open other Issue to ask about problem with browser rendering.
